#!/bin/bash
wait_time=60

while [ ! -f aws-init.txt ]; # aws-init.txt file should be generated by resources/aws-init.sh after successfully creating the ssm parameters and s3 bucket.
do
  if [ "wait_time" == 0 ]; then
    echo "ERROR: looks like aws secret manager has failed !"
    exit 1
  fi
  sleep 1
  ((timeout--))
done