server:
  applicationConnectors:
    - type: http
      port: ${DW_HTTP_PORT:-9080}

  adminConnectors:
    - type: http
      port: ${DW_ADMIN_PORT:-9081}

  requestLog:
    appenders:
      - type: console
        target: stdout
        layout:
          type: access-json

logging:
  level: INFO
  appenders:
    - type: console
      target: stderr
      layout:
        type: json
        timestampFormat: "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
        prettyPrint: ${DW_LOG_JSON_PRETTY_PRINT:-false}
